---
- name: Deploy Dockerized Web App
  hosts: all
  tasks:
    - name: Copy nginx.conf
      copy:
        src: ./nginx.conf
        dest: nginx.conf
        
    - name: Copy docker-compose.yml
      copy:
        src: ./docker-compose.yml
        dest: docker-compose.yml

    - name: Copy Dockerfile
      copy:
        src: ./Dockerfile
        dest: Dockerfile

    - name: install dependencies
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
    - name: add GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: add docker repository to apt
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu noble stable
        state: present
    - name: install docker
      apt:
        name: "{{item}}"
        state: latest
        update_cache: yes
      loop:
        - docker-ce

    - name: check docker is active
      service:
        name: docker
        state: started
        enabled: yes
    - name: Ensure group "docker" exists
      ansible.builtin.group:
        name: docker
        state: present
    - name: adding ubuntu to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Start Docker Compose Services
      community.docker.docker_compose_v2:
        project_src: .
        state: present

